export const all_routes = {

  dashboard:"/dashboard",

  contactDetails: "/crm/customer-details",
  deals: "/crm/deals",
  dealsDetails: "/crm/deals-details",
  dealsKanban: "/crm/deals-kanban",
  contactList: "/crm/customer-list",
  leadsKanban: "/leads-kanban",
  pipeline: "/crm/pipeline",
  shareProfile:"/shareProfile",
  userVerification:"/user-verification",
  registrationForm:"/registration-form",

  contactGrid: "/crm/customer-kanban",

  contactsDetails: "/contacts-details",
  leads: "/leads",
  contacts: "/contacts",
  templates: "/templates",
  // whatsappTemplates: "/templates#whatsappTemplates",
  // emailTemplates: "/templates#emailTemplates",
  emails:"/emails",
  calendar:"/calendar",
  Whatsapp: "/crm/Whatsapp",
  login: "/login",
  register: "/register",
  upgradePlan: "/general-settings/upgrade-plan",
  scans: "/general-settings/scans",
  profile: "/general-settings/profile",
  security: "/general-settings/security",
  emailSetup: "/general-settings/emailSetup",
ImportAndExport:"/import-and-export",
Api:"/api",
SyncAndIntegration:"/sync-and-integration",
HelpAndSupport:"/help-and-support",
Zapier:"/zapier",
  contactReports: "/reports/contact-reports",
  ReferAndEarn: "/refer-and-earn",
  groups: "/groups"
};
